
spring.datasource:
  sql-script-encoding: utf-8
  url: jdbc:h2:mem:testdb;MODE=PostgreSQL

spring.jackson:
  default-property-inclusion: NON_NULL
  serialization:
    indent-output: true
    write-dates-as-timestamps: false

#logging.level:
#  example.adapters.datasource.TaskMapper: DEBUG
